import React from "react";

export const Home = () =>{
    return(
        <>
        <h1>Home</h1>
        <ul>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
        <li>anujaya</li>
    </ul>
    </>
    )
}